# Generated by Django 5.2 on 2025-05-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subdealer', max_length=100)),
                ('phone_number', models.CharField(help_text='Phone number of the subdealer', max_length=15)),
                ('address', models.TextField(help_text='Address of the subdealer')),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage for the subdealer', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubdealerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventory')),
                ('subdealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubDealers.subdealer')),
            ],
        ),
    ]
