# Generated by Django 5.2 on 2025-10-15 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subdealer', max_length=100)),
                ('subdealerCode', models.CharField(help_text='Unique Subdealer Code', max_length=50, unique=True)),
                ('phone_number', models.CharField(help_text='Phone number of the subdealer', max_length=15)),
                ('address', models.TextField(help_text='Address of the subdealer')),
            ],
            options={
                'db_table': 'SubDealers',
            },
        ),
        migrations.CreateModel(
            name='SubDealerSKUDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Subdealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubDealers.subdealer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventory')),
            ],
            options={
                'db_table': 'SubDealer_SKU_Discount',
            },
        ),
    ]
