# Generated by Django 5.2 on 2025-10-22 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'predefined_expenses',
            },
        ),
        migrations.CreateModel(
            name='Subdealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subdealer', max_length=100)),
                ('subdealerCode', models.CharField(help_text='Unique Subdealer Code', max_length=50, unique=True)),
                ('phone_number', models.CharField(help_text='Phone number of the subdealer', max_length=15)),
                ('address', models.TextField(help_text='Address of the subdealer')),
            ],
            options={
                'db_table': 'SubDealers',
            },
        ),
        migrations.CreateModel(
            name='DailyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employees', models.ManyToManyField(to='employees.employee')),
            ],
            options={
                'db_table': 'DailyInvoice',
            },
        ),
        migrations.CreateModel(
            name='DailyInvoiceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='SubDealers.dailyinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='DailyInvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('submitted_blank', models.PositiveIntegerField(default=0)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_cyl', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='SubDealers.dailyinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productinventory')),
                ('subdealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SubDealers.subdealer')),
            ],
        ),
        migrations.CreateModel(
            name='Cylender_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_cylender_qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventory')),
                ('Subdealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubDealers.subdealer')),
            ],
            options={
                'db_table': 'Cylender_information',
            },
        ),
        migrations.CreateModel(
            name='SubDealerSKUDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventory')),
                ('subdealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubDealers.subdealer')),
            ],
            options={
                'db_table': 'SubDealer_SKU_Discount',
                'unique_together': {('subdealer', 'product')},
            },
        ),
    ]
