# Generated by Django 5.2 on 2025-10-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdealerskudiscount',
            old_name='Subdealer',
            new_name='subdealer',
        ),
        migrations.AlterUniqueTogether(
            name='subdealerskudiscount',
            unique_together={('subdealer', 'product')},
        ),
    ]
