# Generated by Django 5.2 on 2025-10-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubDealers', '0002_rename_subdealer_subdealerskudiscount_subdealer_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cylender_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_cylender_qty', models.IntegerField()),
                ('Subdealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubDealers.subdealer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventory')),
            ],
            options={
                'db_table': 'Cylender_information',
            },
        ),
    ]
